Repository arifulbgt4/Marketplace, pull requests merged in 2023-10, with the labels that each got.

#18 fix: ListingBooking
  src/app/[locale]/l/[slug]/page.tsx
  src/app/[locale]/l/page.tsx
  src/middleware.ts
  src/widgets/ListingBooking/Types.ts
  src/widgets/ListingBooking/index.tsx
  src/widgets/ListingDetailsSidebar/Types.ts
  src/widgets/ListingDetailsSidebar/index.tsx
Labels: enhancement, design

#23 fix: typography
  src/theme/typography.ts
Labels: good first issue, invalid, design

#33 fix:logo
  src/components/Logo/index.tsx
Labels: bug

#38 fix: about question
  src/widgets/Question/index.tsx
Labels: good first issue, design

#56 fix: Header
  src/layouts/AuthPagesLayout/index.tsx
  src/widgets/Header/index.tsx
  src/widgets/Listings/index.tsx
  src/widgets/SearchListingGroup/index.tsx
  src/widgets/SigninInfo/index.tsx
  src/widgets/UserListing/index.tsx
Labels: bug, design

#64 feat: empty listing and empty bookmark component
  src/widgets/EmptyBookmark/Types.ts
  src/widgets/EmptyBookmark/index.tsx
  src/widgets/EmptyListing/Types.ts
  src/widgets/EmptyListing/index.tsx
Labels: enhancement, design

#71 feat: ListingRatings
  src/widgets/ListingRatings/Types.tsx
  src/widgets/ListingRatings/index.tsx
Labels: bug, enhancement

#73 fix: filterradio
  src/global/staticData/index.ts
  src/widgets/FilterRadio/Types.ts
  src/widgets/FilterRadio/index.tsx
  src/widgets/ListSearchFilters/index.tsx
Labels: enhancement, design

#76 feat: ListingContents
  src/app/[locale]/l/[slug]/page.tsx
  src/global/staticData/index.ts
  src/widgets/Album/index.tsx
  src/widgets/ListingContents/Types.ts
  src/widgets/ListingContents/index.tsx
  src/widgets/ListingDetailsBanner/Types.ts
  src/widgets/ListingDetailsBanner/index.tsx
  src/widgets/ListingDetailsContent/Types.ts
  src/widgets/ListingDetailsContent/index.tsx
  src/widgets/Review/Types.ts
  src/widgets/Review/index.tsx
  src/widgets/Reviews/Types.ts
  src/widgets/Reviews/index.tsx
Labels: enhancement, design
